[env:m5stick-c-plus2]
platform = espressif32
board = m5stick-c
framework = arduino
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -Os
lib_deps =
    m5stack/M5StickCPlus2
    crankyoldgit/IRremoteESP8266
monitor_speed = 115200
